---
- name: (configure) create samba group
  group:
    name: samba
    gid: "{{ takel_samba_group_id }}"
    state: present

- name: (configure) copy sudo file for samba group member
  copy:
    src: sudo_samba
    dest: /etc/sudoers.d/samba

- name: (configure) copy samba config file
  template:
    src: smb.conf.j2
    dest: "{{ takel_samba_config_file }}"
    validate: 'testparm -s %s'
  notify: restart samba

- name: (configure) ensure samba service(s) are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ takel_samba_services }}"

- name: (configuration) copy config for avahi
  template:
    src: avahi-daemon.conf.j2
    dest: /etc/avahi/avahi-daemon.conf
  notify: restart avahi

- name: (configuration) copy samba config for avahi
  copy:
    src: avahi_samba.service
    dest: /etc/avahi/services/samba.service
  notify: restart avahi
