---
- name: (main) include install tasks
  import_tasks: install.yml
  tags:
    - takel
    - takel_samba
    - takel_samba_install

- name: (main) include configure tasks
  import_tasks: configure.yml
  tags:
    - takel
    - takel_samba
    - takel_samba_configure

- name: (main) include timemachine-scripts tasks
  import_tasks: timemachine-scripts.yml
  tags:
    - takel
    - takel_samba
    - takel_samba_timemachine_scripts
  when: takel_samba_timemachine

- name: (main) include systemd tasks
  import_tasks: systemd.yml
  tags:
    - takel
    - takel_samba
    - takel_samba_systemd

- name: (main) include sshd tasks
  import_tasks: sshd.yml
  tags:
    - takel
    - takel_samba
    - takel_samba_sshd

- name: (main) include users tasks
  import_tasks: users.yml
  tags:
    - takel
    - takel_samba
    - takel_samba_users
