---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint molecule/*/*.yml
  flake8
platforms:
  - name: molecule-takelage-smb-test-image-${TAKELAGE_PROJECT_ENV:-prod}
    image: packer_local/takelage-smb:${TAKELAGE_PROJECT_ENV:-prod}
    override_command: true
    command: >-
      /entrypoint.py
      --username testuser
      --uid 1010
      --gid 1010
      --home /testhome/testuser
      --no-bit
      --no-docker
      --no-git
      --no-gopass
      --no-gpg
      --no-ssh
      --gpg_agent_port 18502
      --gpg_ssh_agent_port 18503
    tty: true
    privileged: true
    pre_build_image: true
    groups:
      - ${TAKELAGE_PROJECT_ENV:-prod}
      - users
      - molecule
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
  options:
    # p: cacheprovider  # enable cache
    s: true  # capture output
    v: true
scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - verify
    - destroy
